### PR TITLE
Add FS Support

### PR DESCRIPTION
**Pull request by UserJHansen**
Adds FS support for the Pico but also the WASM and PC emulators.

### CODE REVIEW

**Comment by shanecelis** [comment]
Hi! Thank you so much for the pull request. I think this functionality looks great and is a welcome addition. I would ask for the following adjustments:

* Don't pass the filesystem through the App interface.
* Introduce a new function `trowel::take_filesystem()` or perhaps model it on `let mut pac = pac::Peripherals::take().unwrap();`. Trowel only has to provide it once. If an app wants it, they can store it themselves.
* Remove .vscode from commit
* Suggest reading and writing u8s `fn read_file(&mut self, name: &str, &mut [u8]) -> Result(usize, _);`
* `read_file` doesn't know how many bytes it read or whether it succeeded in reading. Also this places a limit on the size of the files that can be written.

I wish the sdcard lib offered iterators instead of closure callbacks, then we could probably avoid using `Vec<>` for listing files. I see you're pointing to your own repo for sdcard. What changes did you have to make? Maybe we can add some iterators there.

Side note: I'm excited about this functionality. Once this pull request integrated, I'd love for trowel to perhaps include a start up screen akin to a bios screen where the user can press a button before the regular game loads, and with an sdcard we could then list other loadable files.

Thank you for submitting this pull request. It's good work.

**Comment by UserJHansen** [comment]
The issue with not passing the filesystem like that is the filesystem cannot be accessed during the render phase due to contention on the SPI bus. What do you think the best solution for that would be?

The changes made to the sdcard lib was part of a pull request by another user that has yet to be merged, so just using my fork for the moment. 

The size of the buffer for reading files is dynamic but it is based on the length of the file, so I think that letting it be generated in the function could be better. I think returning a optional instead of a result could be better so it wouldn't push all the different possible error values onto the user. This would make the signature: `fn read_file(&mut self, name: &str) -> Option<(usize, &[u8])>`

Edit: I looked at returning [u8] and it would have to be in a box on heap

**Comment by shanecelis** [comment]
Ah, I see now what you mean about the chip select for the sdcard. How about this as an API suggestion:

```
pub trait App
{
    fn init(&mut self) -> AppResult;
    fn update(&mut self, buttons: Buttons) -> AppResult;
    fn draw<T,E>(&mut self, display: &mut T) -> AppResult
        where T: DrawTarget<Color = Rgb565, Error = E>;
    fn read_write<F>(file_system: F) -> AppResult
        where F : fs::FS {
        // Default implementation does nothing.
        Ok(())
    }
}
```

I like the use of Option over a non-error result.

**Comment by UserJHansen** [comment]
Awesome, got all those fixed. The pull request on embedded-sdmmc has been merged, a new release just hasn't been created so waiting for that.

**Comment by shanecelis** [comment]
All right. It's integrated. Thank you!

**Pull request closed without merging**
